// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt5j9x7L3MKClF-mnmLXMLbf1fpHgl3pE',
    appId: '1:437694063639:android:6f0b446c39a3bc9adfe852',
    messagingSenderId: '437694063639',
    projectId: 'desafioloomi-18686',
    storageBucket: 'desafioloomi-18686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgHd0vrHMDdPsUs24IXTYA5Xs6sPZvdVw',
    appId: '1:437694063639:ios:42e17150364747afdfe852',
    messagingSenderId: '437694063639',
    projectId: 'desafioloomi-18686',
    storageBucket: 'desafioloomi-18686.firebasestorage.app',
    androidClientId: '437694063639-p1ltqd1o21fnu2fnucid1fh22qvrv94v.apps.googleusercontent.com',
    iosClientId: '437694063639-91lafa0fkdjl3832gadbqs45margp5h4.apps.googleusercontent.com',
    iosBundleId: 'br.com.furlaneto.murilo.desafioLoomi',
  );
}
